name: Continuous Integration
on: [pull_request]
jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn let-build
      - name: Test
        run: yarn test --watchAll=false
      - uses: ravsamhq/notify-slack-action@v1
        if: always()
        with:
            status: ${{ job.status }}
            token: ${{ secrets.GITHUB_TOKEN }}
            notification_title: '{workflow} has {status_message}'
            message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>'
            footer: 'Linked Repo <{repo_url}|{repo}> | <{workflow_url}|View Workflow>'
            notify_when: 'failure'
        env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - uses: dawidd6/action-send-mail@v2
        if: failure()
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.SECRET_EMAIL }}
          password: ${{ secrets.SECRET_EMAIL_PASSWORD }}
          # email subject
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          # email body as text
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          # comma-separated string, send email to
          to: thienho1998dragon@gmail.com,vunam1218@gmail.com,nguyenhoanganh806@gmail.com
            # from email name
          from: K16_HW3_CICD